AWSTemplateFormatVersion: '2010-09-09'
Description: Git 2 S3
Mappings:
  LambdaBuckets:
    us-east-1:
      Name: git-to-codepipeline-prod-us-east-1
    us-west-2:
      Name: git-to-codepipeline-prod-us-west-2
    eu-west-1:
      Name: git-to-codepipeline-prod-eu-west-1
Conditions:
  UseAllowedIps: !Not
    - !Equals
      - !Ref AllowedIps
      - ''
  UseApiSecret: !Not
    - !Equals
      - !Ref ApiSecret
      - ''
  UseBranch: !Not
    - !Equals
      - !Ref Branch
      - ''
  UseOutputFiles: !Not
    - !Equals
      - !Ref OutputFiles
      - ''
  AutoGenOutputBucketName: !Not
    - !Equals
      - !Ref OutputBucketName
      - ''
Parameters:
  Git2S3Bucket:
    Description: Specify bucket name where lambda code (git2s3.zip) is located
    Type: String
  Branch:
    Description: >-
      OPTIONAL: Specify which branch(es) you want to follow.
      All branches if left blank
    Type: String
    Default: ''
  OutputBucketName:
    Description: >-
      OPTIONAL: Bucket Name where the zip file output should be placed, if left
      blank a bucket name will be automatically generated.
    Type: String
    Default: ''
  OutputFiles:
    Description: Output artifacts (all files by default)
    Type: String
    Default: ''
  AllowedIps:
    Description: >-
      gitpull method only. Comma seperated list of IP CIDR blocks for source IP
      authentication. The BitBucket Cloud IP ranges are provided as defaults.
    Type: String
    Default: '131.103.20.160/27,165.254.145.0/26,104.192.143.0/24'
  ApiSecret:
    Description: >-
      WebHook Secrets for use with GitHub Enterprise and GitLab.
      If a secret is matched IP range authentication is bypassed.
      Cannot contain: , \ "
    Type: String
    Default: ''
    NoEcho: 'true'
  MaxMemory:
    Description: Your function is allocated CPU proportional to the memory configured.
    Type: String
    Default: 128
Resources:
  KeyBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
  OutputBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !If
        - AutoGenOutputBucketName
        - !Ref OutputBucketName
        - !Ref 'AWS::NoValue'
      VersioningConfiguration:
        Status: Enabled
  KMSKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: 'Bucket to store ssh keys'
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Allow access for Key Administrators
            Effect: Allow
            Principal:
              AWS:
                - !Join
                  - ''
                  - - 'arn:aws:iam::'
                    - !Ref 'AWS::AccountId'
                    - ':root'
            Action:
              - 'kms:Create*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Update*'
              - 'kms:Revoke*'
              - 'kms:Disable*'
              - 'kms:Get*'
              - 'kms:Delete*'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
            Resource: '*'
          - Sid: Allow use of the key
            Effect: Allow
            Principal:
              AWS:
                - !Join
                  - ''
                  - - 'arn:aws:iam::'
                    - !Ref 'AWS::AccountId'
                    - ':root'
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'
          - Sid: Allow attachment of persistent resources
            Effect: Allow
            Principal:
              AWS:
                - !Join
                  - ''
                  - - 'arn:aws:iam::'
                    - !Ref 'AWS::AccountId'
                    - ':root'
            Action:
              - 'kms:CreateGrant'
              - 'kms:ListGrants'
              - 'kms:RevokeGrant'
            Resource: '*'
            Condition:
              Bool:
                'kms:GrantIsForAWSResource': true
  CreateSSHKeyRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: !Sub
            - ${StackName}-sshkeygen
            - StackName: !Ref 'AWS::StackName'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                Resource:
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - !Ref KeyBucket
                      - /crypto.zip
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                Resource:
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - !Ref KeyBucket
                      - /enc_key
              - Effect: Allow
                Action:
                  - 'kms:Encrypt'
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - 'arn:aws:logs:*:*:*'
  CreateSSHKeyLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      MemorySize: '128'
      Role: !GetAtt
        - CreateSSHKeyRole
        - Arn
      Runtime: python2.7
      Timeout: '300'
      Code:
        S3Bucket: !FindInMap
          - LambdaBuckets
          - !Ref 'AWS::Region'
          - Name
        S3Key: v1.0/CreateSSHKey.zip
  CreateSSHKey:
    Type: 'AWS::CloudFormation::CustomResource'
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt
        - CreateSSHKeyLambda
        - Arn
      KeyBucket: !Ref KeyBucket
      Region: !Ref 'AWS::Region'
      KMSKey: !Ref KMSKey
  Git2S3Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: '/'
      Policies:
        -
          PolicyName: substance-codebuild
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action:
                  - 'logs:DescribeLogGroups'
                  - 'logs:CreateLogGroup'
                  - 'logs:DeleteLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 'logs:PutRetentionPolicy'
                  - 's3:*'
                  - 'kms:*'
                  - 'lambda:*'
                  - 'sns:*'
                  - 'cloudformation:*'
                  - 'iam:GetRole'
                Resource: '*'
  Git2S3LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub
        - /aws/lambda/${StackName}
        - StackName: !Ref 'AWS::StackName'
  Git2S3Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      MemorySize: !Ref MaxMemory
      Role: !GetAtt
        - Git2S3Role
        - Arn
      Runtime: nodejs6.10
      Timeout: '300'
      Code:
        S3Bucket: !Ref Git2S3Bucket
        S3Key: git2s3/git2s3.zip
  Git2S3ApiGateLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      MemorySize: '128'
      Role: !GetAtt
        - Git2S3Role
        - Arn
      Runtime: nodejs6.10
      Timeout: '300'
      Code:
        ZipFile: !Join
          - ""
          - - "var AWS = require('aws-sdk');"
            - "exports.handler = (event, context, callback) => {"
            - "    var lambda = new AWS.Lambda();"
            - "    var args = JSON.stringify({"
            - "        body: event.body,"
            - "        stageVariables: event.stageVariables"
            - "    });"
            - "    var params = {"
            - "        FunctionName: '"
            - !GetAtt
              - Git2S3Lambda
              - Arn
            - "',"
            - "        InvokeArgs: args"
            - "    };"
            - "    lambda.invokeAsync(params, function(err, data) {"
            - "        if (err) {"
            - "            console.log(err, err.stack);"
            - "        }"
            - "    });"
            - "    callback(null, {"
            - "        statusCode: 200,"
            - "        body: ''"
            - "    });"
            - "};"
  WebHookRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - >-
          arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      Policies:
        - PolicyName: !Sub
          - ${StackName}-webhook
          - StackName: !Ref 'AWS::StackName'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'lambda:InvokeAsync'
                  - 'lambda:InvokeFunction'
                Resource:
                  - !GetAtt
                    - Git2S3ApiGateLambda
                    - Arn
  WebHookApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: !Ref 'AWS::StackName'
      Description: Git 2 S3 Rest API
      Body:
        swagger: '2.0'
        info:
          version: '1.0'
          title: !Ref 'AWS::StackName'
        schemes:
          - https
        paths:
          /gitpull:
            post:
              consumes:
                - application/json
              produces:
                - application/json
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: '200'
                uri: !Join
                  - ''
                  - - 'arn:aws:apigateway:'
                    - !Ref 'AWS::Region'
                    - ':lambda:path/2015-03-31/functions/'
                    - !GetAtt
                      - Git2S3ApiGateLambda
                      - Arn
                    - /invocations
                passthroughBehavior: when_no_match
                httpMethod: POST
                credentials: !GetAtt
                  - WebHookRole
                  - Arn
                type: aws_proxy
  WebHookApiDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref WebHookApi
  WebHookApiProdStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      DeploymentId: !Ref WebHookApiDeployment
      RestApiId: !Ref WebHookApi
      StageName: Prod
      Variables:
        StackName: !Ref 'AWS::StackName'
Outputs:
  PublicSSHKey:
    Value: !Ref CreateSSHKey
  Git2S3WebHookApi:
    Value: !Join
      - ''
      - - ' https://'
        - !Ref WebHookApi
        - .execute-api.
        - !Ref 'AWS::Region'
        - .amazonaws.com/
        - !Ref WebHookApiProdStage
        - /gitpull
    Export:
      Name: !Sub ${AWS::StackName}-webhook
  OutputBucketName:
    Value: !Ref OutputBucket
    Export:
      Name: !Sub ${AWS::StackName}-output-bucket
  KeyBucketName:
    Value: !Ref KeyBucket
  AllowedIps:
    Value: !Ref AllowedIps
  ApiSecret:
    Value: !Ref ApiSecret
  Branch:
    Value: !Ref Branch
  OutputFiles:
    Value: !Ref OutputFiles
